package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
)

const (
	generateComment = "// generate:reset"
	outputFile      = "reset.gen.go"
)

func main() {
	dir, err := os.Getwd()
	if err != nil {
		log.Fatalf("os.Getwd: %v", err)
	}

	err = filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		if strings.HasPrefix(path, ".") || strings.HasPrefix(path, "vendor") {
			return filepath.SkipDir
		}

		pkgs, err := parser.ParseDir(token.NewFileSet(), path, nil, parser.ParseComments)
		if err != nil {
			return err
		}

		for pkgName, pkg := range pkgs {
			var resetFuncs []string

			for _, file := range pkg.Files {
				for _, decl := range file.Decls {
					genDecl, ok := decl.(*ast.GenDecl)
					if !ok || genDecl.Tok != token.TYPE {
						continue
					}

					for _, spec := range genDecl.Specs {
						typeSpec, ok := spec.(*ast.TypeSpec)
						if !ok {
							continue
						}

						structType, ok := typeSpec.Type.(*ast.StructType)
						if !ok {
							continue
						}

						if hasGenerateComment(genDecl) {
							resetFuncs = append(resetFuncs, generateResetFunc(typeSpec.Name.Name, structType))
						}
					}
				}
			}

			if len(resetFuncs) > 0 {
				return writeResetFile(path, pkgName, resetFuncs)
			}
		}
		return nil
	})
	if err != nil {
		log.Fatalf("Error walking through the project: %v", err)
	}
}

func hasGenerateComment(decl *ast.GenDecl) bool {
	if decl.Doc == nil {
		return false
	}
	for _, comment := range decl.Doc.List {
		if strings.TrimSpace(comment.Text) == generateComment {
			return true
		}
	}
	return false
}

func generateResetFunc(structName string, structType *ast.StructType) string {
	var body strings.Builder
	fmt.Fprintf(&body, "func (rs *%s) Reset() {\n", structName)
	fmt.Fprintln(&body, "if rs == nil {")
	fmt.Fprintln(&body, "return")
	fmt.Fprintln(&body, "}")
	fmt.Fprintln(&body)

	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		fieldName := field.Names[0].Name
		switch t := field.Type.(type) {
		case *ast.Ident: // Primitives
			switch t.Name {
			case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "float32", "float64", "complex64", "complex128":
				fmt.Fprintf(&body, "rs.%s = 0\n", fieldName)
			case "string":
				fmt.Fprintf(&body, `rs.%s = ""%s`, fieldName, "\n")
			case "bool":
				fmt.Fprintf(&body, "rs.%s = false\n", fieldName)
			}
		case *ast.ArrayType: // Slices
			fmt.Fprintf(&body, "rs.%s = rs.%s[:0]\n", fieldName, fieldName)
		case *ast.MapType: // Maps
			fmt.Fprintf(&body, "clear(rs.%s)\n", fieldName)
		case *ast.StarExpr: // Pointers
			fmt.Fprintf(&body, "if rs.%s != nil {\n", fieldName)
			if ident, ok := t.X.(*ast.Ident); ok {
				switch ident.Name {
				case "string":
					fmt.Fprintf(&body, `*rs.%s = ""%s`, fieldName, "\n")
				case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "float32", "float64", "complex64", "complex128":
					fmt.Fprintf(&body, "*rs.%s = 0\n", fieldName)
				case "bool":
					fmt.Fprintf(&body, "*rs.%s = false\n", fieldName)
				default:
					fmt.Fprintf(&body, "if resetter, ok := interface{}(rs.%s).(interface{ Reset() }); ok {\n", fieldName)
					fmt.Fprintln(&body, "resetter.Reset()")
					fmt.Fprintln(&body, "}")
				}
			} else {
				fmt.Fprintf(&body, "if resetter, ok := interface{}(rs.%s).(interface{ Reset() }); ok {\n", fieldName)
				fmt.Fprintln(&body, "resetter.Reset()")
				fmt.Fprintln(&body, "}")
			}
			fmt.Fprintln(&body, "}")
		case *ast.SelectorExpr:
			fmt.Fprintf(&body, "if resetter, ok := interface{}(&rs.%s).(interface{ Reset() }); ok {\n", fieldName)
			fmt.Fprintln(&body, "resetter.Reset()")
			fmt.Fprintln(&body, "}")
		}
	}

	fmt.Fprintln(&body, "}")
	return body.String()
}

func writeResetFile(path, pkgName string, funcs []string) error {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by reset-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	buf.WriteString(strings.Join(funcs, "\n\n"))

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("error formatting generated code: %v\n%s", err, buf.String())
	}

	return os.WriteFile(filepath.Join(path, outputFile), formatted, 0644)
}
